# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Eusebius Ngemera

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-production:
        dependency-type: production
        patterns:
          - "*"
      npm-development:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
