// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Eusebius Ngemera

import { useMemo, useState } from "react";
import { auditLibrary, type FindingId } from "../lib/audit";
import { diffLibraries } from "../lib/diff";
import { buildLibrary, type MediaItem, type MediaLibrary, type PlaylistNode } from "../lib/model";
import {
  applyOperations,
  exportFilename,
  exportOperations,
  type Operation,
} from "../lib/operations";
import type { LoadedFile } from "../lib/loadFile";
import { useI18n } from "../i18n";

/**
 * Queue edits, review them, and export a new file.
 *
 * Nothing is applied to the loaded document as you go. Operations accumulate in
 * a list, the edited library is recomputed from them for the preview, and the
 * file is only produced on export. That makes every change undoable for free,
 * and means the summary of what you are about to do is generated by the same
 * diff engine the Diff tab uses rather than by bookkeeping that could drift.
 */
/** A queued fix, with enough detail to show its working before applying it. */
interface QuickFix {
  /** The audit finding this came from, so the reader can go and see it. */
  finding: FindingId;
  label: string;
  why: string;
  operations: Operation[];
  /** One line per thing that would change. */
  affected: {
    key: string;
    primary: string;
    secondary: string;
    /**
     * The copy being dropped carries a different label from the one kept.
     *
     * Worth flagging: the fix keeps whichever comes first, which is not
     * necessarily the one whose name someone actually chose.
     */
    warn?: boolean;
  }[];
}

export function ReorganiseView({
  file,
  onShowInAudit,
}: {
  file: LoadedFile;
  /** Switch to the Audit tab and highlight a finding. */
  onShowInAudit?: (finding: FindingId) => void;
}) {
  const i18n = useI18n();
  const { t, f, num, plural } = i18n;
  const r = t.tools.mediaBin.reorganise;

  const [operations, setOperations] = useState<Operation[]>([]);
  const [exported, setExported] = useState<string | null>(null);

  const queue = (...added: Operation[]) => {
    setOperations((prev) => [...prev, ...added]);
    setExported(null);
  };

  // An operation can stop applying if an earlier one removed what it names.
  // Rather than police that when queueing, apply the whole list and let a
  // failure surface as something to undo.
  const editedDoc = useMemo(() => {
    try {
      return applyOperations(file.doc, operations);
    } catch {
      return null;
    }
  }, [file.doc, operations]);

  const editedLib = useMemo<MediaLibrary | null>(
    () => (editedDoc ? buildLibrary(editedDoc) : null),
    [editedDoc]
  );

  const pendingDiff = useMemo(
    () => (editedLib ? diffLibraries(file.library, editedLib) : null),
    [file.library, editedLib]
  );

  // Quick fixes come from auditing the *edited* library, so an applied fix
  // stops being offered.
  const audit = useMemo(() => (editedLib ? auditLibrary(editedLib) : null), [editedLib]);

  const describeItem = (item: MediaItem) => ({
    key: item.uuid,
    primary: f(r.affectedItem, {
      name: item.name || item.displayFilename,
      playlist: item.playlistPath || t.diff.root,
    }),
    secondary: item.relativePath || item.absolutePath,
  });

  const duplicateFix = useMemo<QuickFix | null>(() => {
    if (!audit || audit.withinPlaylistDuplicates.length === 0) return null;

    const operations: Operation[] = [];
    const affected: QuickFix["affected"] = [];

    for (const group of audit.withinPlaylistDuplicates) {
      for (const path of group.repeatedWithin) {
        const inPlaylist = group.items.filter((item) => item.playlistPath === path);
        const [kept, ...surplus] = inPlaylist;
        for (const item of surplus) {
          operations.push({
            kind: "removeItem",
            playlistUuid: item.playlistUuid,
            itemUuid: item.uuid,
            itemName: item.name || item.displayFilename,
          });
          const row = describeItem(item);
          const keptName = kept.name || kept.displayFilename;
          affected.push({
            ...row,
            secondary: `${row.secondary} · ${f(r.keeping, { name: keptName })}`,
            warn: (item.name || item.displayFilename) !== keptName,
          });
        }
      }
    }

    return operations.length
      ? {
          finding: "withinPlaylist",
          label: plural(r.removeDuplicates, operations.length),
          why: r.removeDuplicatesWhy,
          operations,
          affected,
        }
      : null;
  }, [audit, f, plural, r, t]);

  const emptyPlaylistFix = useMemo<QuickFix | null>(() => {
    if (!editedLib) return null;

    const operations: Operation[] = [];
    const affected: QuickFix["affected"] = [];
    (function walk(node: PlaylistNode) {
      if (node.kind !== "root" && node.items.length === 0 && node.children.length === 0) {
        operations.push({
          kind: "removePlaylist",
          playlistUuid: node.uuid,
          playlistName: node.name,
        });
        affected.push({ key: node.uuid, primary: node.path, secondary: r.emptyPlaylist });
      }
      node.children.forEach(walk);
    })(editedLib.root);

    return operations.length
      ? {
          finding: "empty",
          label: plural(r.removeEmpty, operations.length),
          why: r.removeEmptyWhy,
          operations,
          affected,
        }
      : null;
  }, [editedLib, plural, r]);

  const quickFixes = [duplicateFix, emptyPlaylistFix].filter((fix): fix is QuickFix => fix !== null);

  function download() {
    const bytes = exportOperations(file.doc, operations);
    const name = exportFilename(file.filename);
    const url = URL.createObjectURL(
      new Blob([bytes as BlobPart], { type: "application/octet-stream" })
    );

    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = name;
    // Some browsers ignore a click on an anchor that is not in the document.
    anchor.style.display = "none";
    document.body.append(anchor);
    anchor.click();
    anchor.remove();

    // Revoking synchronously can pull the blob away before the browser has
    // finished reading it -- Safari is the usual casualty. Let the current task
    // finish first.
    setTimeout(() => URL.revokeObjectURL(url), 0);

    setExported(name);
  }

  const total = operations.length;

  return (
    <>
      <div className="card">
        <h2>{r.heading}</h2>
        <p className="sub">{r.intro}</p>

        <div className="editor-bar">
          <span className="editor-count">
            {total === 0 ? r.none : plural(r.pending, total)}
          </span>
          <span className="spacer" />
          <button className="btn" disabled={total === 0} onClick={() => setOperations((p) => p.slice(0, -1))}>
            {r.undo}
          </button>
          <button className="btn" disabled={total === 0} onClick={() => setOperations([])}>
            {r.discard}
          </button>
          <button
            className="btn primary"
            disabled={total === 0 || !file.exportSafe || !editedDoc}
            title={file.exportSafe ? undefined : r.exportBlocked}
            onClick={download}
          >
            {r.exportFile}
          </button>
        </div>

        {!file.exportSafe && <p className="why warn-inline">{r.exportBlocked}</p>}
        {!editedDoc && <p className="why warn-inline">{r.broken}</p>}
        {exported && <p className="why">{f(r.exportedAs, { filename: exported })}</p>}

        {pendingDiff && total > 0 && (
          <div className="stats" style={{ marginTop: 12 }}>
            {(["added", "removed", "moved", "renamed"] as const).map((kind) => (
              <div className="stat" key={kind}>
                <div className="n" style={{ color: `var(--${kind})` }}>
                  {num(pendingDiff.counts[kind])}
                </div>
                <div className="l">{t.diff.types[kind]}</div>
              </div>
            ))}
            {/* Playlist edits are not item changes, so without this a queue of
                nothing but renamed or removed playlists reads as all zeros. */}
            <div className="stat">
              <div className="n">{num(pendingDiff.playlistChanges.length)}</div>
              <div className="l">{t.diff.playlistStructure}</div>
            </div>
          </div>
        )}
      </div>

      <div className="card">
        <h2>{r.quickFixes}</h2>
        <p className="sub">{r.quickFixesWhy}</p>

        {quickFixes.length === 0 ? (
          <p className="sub">{r.nothingToFix}</p>
        ) : (
          <ul className="rows">
            {quickFixes.map((fix) => (
              <li key={fix.finding}>
                <div className="editor-bar" style={{ padding: 0 }}>
                  <button className="btn" onClick={() => queue(...fix.operations)}>
                    {fix.label}
                  </button>
                  {onShowInAudit && (
                    <button className="btn" onClick={() => onShowInAudit(fix.finding)}>
                      {r.viewInAudit}
                    </button>
                  )}
                </div>
                <div className="why" style={{ marginTop: 4 }}>{fix.why}</div>

                {/* Applying a fix should never be a leap of faith: the exact
                    rows it would touch are one click away. */}
                <details className="more">
                  <summary>{r.showAffected}</summary>
                  <ul className="rows">
                    {fix.affected.map((row) => (
                      <li key={row.key}>
                        <div>
                          {row.primary}
                          {row.warn && (
                            <span className="warn-inline"> — {r.differentName}</span>
                          )}
                        </div>
                        <div className="path">{row.secondary}</div>
                      </li>
                    ))}
                  </ul>
                </details>
              </li>
            ))}
          </ul>
        )}
      </div>

      {editedLib && (
        <div className="card">
          <h2>{t.browse.heading}</h2>
          <p className="sub">
            {f(t.browse.subtitle, {
              items: plural(t.browse.items, editedLib.items.length),
              playlists: plural(t.browse.playlists, editedLib.playlists.length),
            })}
          </p>

          <ul className="tree">
            {editedLib.root.children.map((node) => (
              <EditableNode
                key={node.uuid || node.path}
                node={node}
                library={editedLib}
                depth={0}
                queue={queue}
              />
            ))}
          </ul>
        </div>
      )}
    </>
  );
}

function EditableNode({
  node,
  library,
  depth,
  queue,
}: {
  node: PlaylistNode;
  library: MediaLibrary;
  depth: number;
  queue: (...ops: Operation[]) => void;
}) {
  const { t, f, num, plural } = useI18n();
  const r = t.tools.mediaBin.reorganise;
  const hasChildren = node.children.length > 0;

  function renamePlaylist() {
    const next = window.prompt(r.renamePlaylistPrompt, node.name);
    if (next && next !== node.name) {
      queue({ kind: "renamePlaylist", playlistUuid: node.uuid, from: node.name, to: next });
    }
  }

  function removePlaylist() {
    const ok = window.confirm(
      f(r.removePlaylistConfirm, { name: node.name, n: num(node.items.length) })
    );
    if (ok) queue({ kind: "removePlaylist", playlistUuid: node.uuid, playlistName: node.name });
  }

  return (
    <li>
      <details open={depth < 1}>
        <summary>
          <span className="node-name">{node.name || t.browse.unnamed}</span>
          <span className="node-count">
            {node.items.length > 0 && plural(t.browse.itemCount, node.items.length)}
            {node.items.length === 0 && !hasChildren && r.emptyPlaylist}
          </span>
          <span className="spacer" />
          <span className="row-actions">
            <button className="mini" onClick={(e) => { e.preventDefault(); renamePlaylist(); }}>
              {r.rename}
            </button>
            <button className="mini danger" onClick={(e) => { e.preventDefault(); removePlaylist(); }}>
              {r.remove}
            </button>
          </span>
        </summary>

        <ul>
          {node.items.map((item, index) => (
            <EditableItem
              key={item.uuid || `${item.key}-${index}`}
              item={item}
              index={index}
              playlist={node}
              library={library}
              queue={queue}
            />
          ))}
          {node.children.map((child) => (
            <EditableNode
              key={child.uuid || child.path}
              node={child}
              library={library}
              depth={depth + 1}
              queue={queue}
            />
          ))}
        </ul>
      </details>
    </li>
  );
}

function EditableItem({
  item,
  index,
  playlist,
  library,
  queue,
}: {
  item: MediaLibrary["items"][number];
  index: number;
  playlist: PlaylistNode;
  library: MediaLibrary;
  queue: (...ops: Operation[]) => void;
}) {
  const { t } = useI18n();
  const r = t.tools.mediaBin.reorganise;
  const label = item.name || item.displayFilename;

  function rename() {
    const next = window.prompt(r.renameItemPrompt, item.name);
    if (next && next !== item.name) {
      queue({ kind: "renameItem", itemUuid: item.uuid, from: item.name, to: next });
    }
  }

  return (
    <li className="leaf editable">
      <span className="item-name">{label}</span>
      <span className="item-path">{item.relativePath || item.absolutePath}</span>
      <span className="spacer" />
      <span className="row-actions">
        <button
          className="mini"
          disabled={index === 0}
          title={r.moveUp}
          onClick={() =>
            queue({
              kind: "reorderItem",
              playlistUuid: playlist.uuid,
              itemUuid: item.uuid,
              itemName: label,
              toIndex: index - 1,
            })
          }
        >
          ↑
        </button>
        <button
          className="mini"
          disabled={index === playlist.items.length - 1}
          title={r.moveDown}
          onClick={() =>
            queue({
              kind: "reorderItem",
              playlistUuid: playlist.uuid,
              itemUuid: item.uuid,
              itemName: label,
              toIndex: index + 1,
            })
          }
        >
          ↓
        </button>
        <select
          className="mini"
          aria-label={r.moveTo}
          value=""
          onChange={(e) => {
            if (!e.target.value) return;
            queue({
              kind: "moveItem",
              itemUuid: item.uuid,
              itemName: label,
              fromPlaylistUuid: playlist.uuid,
              toPlaylistUuid: e.target.value,
            });
          }}
        >
          <option value="">{r.moveTo}</option>
          {library.playlists
            .filter((p) => p.uuid !== playlist.uuid)
            .map((p) => (
              <option key={p.uuid} value={p.uuid}>
                {p.path}
              </option>
            ))}
        </select>
        <button className="mini" onClick={rename}>
          {r.rename}
        </button>
        <button
          className="mini danger"
          onClick={() =>
            queue({
              kind: "removeItem",
              playlistUuid: playlist.uuid,
              itemUuid: item.uuid,
              itemName: label,
            })
          }
        >
          {r.remove}
        </button>
      </span>
    </li>
  );
}
